### PR TITLE
added correct links to the content cards for the programs page

### PR DESCRIPTION
**Pull request by andylushman**
Updated the links for the button on the content cards that are located on the `programs` page.

Noticed this will I was working on the `About` page.

### CODE REVIEW

**Comment by scpaye506** [comment]
not sure these urls are exactly correct. there's also a story about changing some of the program sub nav menu items.

**Comment by andylushman** [comment]
@scpaye506 , got it. Should I go ahead and `close` this PR?

**Comment by scpaye506** [comment]
yeah i think just close for now

**Comment by andylushman** [comment]
Closing...

**Pull request closed without merging**
