### PR TITLE
Add featured_on_homepage to publishings model

### LINKED ISSUE #517: Add logic to populate "featured sessions & articles" on the homepage
Probably as an attribute on the publishings model

### PR DESCRIPTION
**Pull request by jayzes**
Allow it to be edited in the admin as well

Fixes #517

### CODE REVIEW

**Comment by jayzes** [comment]
@ryefinegan @scpaye506 i didn't put in the randomization logic (yet) but figure this can get us started

**Comment by scpaye506** [comment]
awesome! Should this also be added to Submissions?

**Comment by jayzes** [comment]
@scpaye506 just squashed this down to a single commit - I'm guessing I should probably cherry-pick it back to the `staging` branch? as well? I don't think #537 needs the same treatment though I could be wrong.

**Comment by scpaye506** [comment]
@jayzes I don't think any need to cherry pick to staging. I'll just merge master directly into staging once this and https://github.com/denverstartupweek/dsw-site/pull/537 are both merged

**Pull request merged**
