### PR TITLE
updated program copy

### PR DESCRIPTION
**Pull request by andylushman**

### CODE REVIEW

**Comment by scpaye506** [comment]
@jayzes that edit profile test is causing random failures it seems

**Comment by jayzes** [comment]
@scpaye506 just pended that out in https://github.com/denverstartupweek/dsw-site/commit/a0b5884036732617e177615e08e2476c001bcd6e

**Comment by andylushman** [comment]
> @scpaye506 just pended that out in [a0b5884](https://github.com/denverstartupweek/dsw-site/commit/a0b5884036732617e177615e08e2476c001bcd6e)

@jayzes , looks like it is still throwing an error...
```
Failures:
  1) Editing my profile Editing an account from the edit profile page FIXED
     Expected pending 'flaky' to fail. No error was raised.
     # ./spec/features/editing_profile_spec.rb:8
```

**Comment by scpaye506** [comment]
> > @scpaye506 just pended that out in [a0b5884](https://github.com/denverstartupweek/dsw-site/commit/a0b5884036732617e177615e08e2476c001bcd6e)
> 
> @jayzes , looks like it is still throwing an error...
> 
> ```
> Failures:
>   1) Editing my profile Editing an account from the edit profile page FIXED
>      Expected pending 'flaky' to fail. No error was raised.
>      # ./spec/features/editing_profile_spec.rb:8
> ```

this is funny, so what happens is that `pending` tests actually fail if the test would have passed. So with the flaky nature of this, it will randomly fail with `pending` or without `pending`

**Comment by andylushman** [comment]
> > > @scpaye506 just pended that out in [a0b5884](https://github.com/denverstartupweek/dsw-site/commit/a0b5884036732617e177615e08e2476c001bcd6e)
> > 
> > 
> > @jayzes , looks like it is still throwing an error...
> > ```
> > Failures:
> >   1) Editing my profile Editing an account from the edit profile page FIXED
> >      Expected pending 'flaky' to fail. No error was raised.
> >      # ./spec/features/editing_profile_spec.rb:8
> > ```
> 
> this is funny, so what happens is that `pending` tests actually fail if the test would have passed. So with the flaky nature of this, it will randomly fail with `pending` or without `pending`

yeah, when I first encountered it, I had and add and removed `pending` a couple of times to find out that it was `flaky`.

**Comment by jayzes** [comment]
Ah, good catch! I wasn't aware of that. Looks like we maybe want `xit` instead? https://relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples#temporarily-pending-by-changing-%22it%22-to-%22xit%22

**Comment by scpaye506** [comment]
yeah probably should just use an `xit` here

**Comment by andylushman** [comment]
Works!

**Pull request merged**
